export const brand = {
  name: 'Marvinho Limited',
  shortName: 'Marvinho',
  tagline: 'Premium Services. Trusted Excellence.',
  description: "Nigeria's premier multi-service corporation delivering excellence across media production, facility management, domestic services, construction finishing, and general merchandise.",
  foundedYear: 2014,
  logo: {
    primary: '/logo.svg',
    dark: '/logo-dark.svg',
    light: '/logo-light.svg',
    favicon: '/favicon.ico',
    icon: '/icon.png',
  },
  colors: {
    gold: '#C9A84C',
    goldLight: '#f9ecc0',
    goldDark: '#9a7522',
    black: '#141414',
    charcoal: '#2D2D2D',
    white: '#ffffff',
    gray: {
      50: '#f9fafb',
      100: '#f3f4f6',
      200: '#e5e7eb',
      300: '#d1d5db',
      400: '#9ca3af',
      500: '#6b7280',
      600: '#4b5563',
      700: '#374151',
      800: '#1f2937',
      900: '#111827',
    },
  },
  fonts: {
    heading: 'Manrope',
    body: 'Inter',
  },
  social: {
    twitter: 'https://twitter.com/marvinho',
    instagram: 'https://instagram.com/marvinho',
    facebook: 'https://facebook.com/marvinho',
    linkedin: 'https://linkedin.com/company/marvinho',
    youtube: 'https://youtube.com/@marvinho',
  },
} as const;
